apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{#toLowerCase application.sanitizedName}}{{/toLowerCase}}
spec:
  template:
    spec:
      containers:
        - image: $IMAGE_REPOSITORY
          ports:
            - containerPort: {{ deploy_options.servicePorts.http }}
      imagePullSecrets:
        - name: $IMAGE_PULL_SECRET_NAME
