apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: "{{tag '  .Chart.Name '}}"
    chart: '{{tag ' .Chart.Name '}}-{{tag ' .Chart.Version | replace "+" "_" '}}'
  name: "{{tag '  .Chart.Name '}}-deployment"
spec:
  replicas: {{tag ' .Values.replicaCount '}}
  revisionHistoryLimit: {{tag ' .Values.revisionHistoryLimit '}}
  selector: 
    matchLabels:
      app: "{{tag '  .Chart.Name '}}"
      version: "current"
  template:
    metadata:
      labels:
        app: "{{tag '  .Chart.Name '}}"
        version: "current"
    spec:
      containers:
      - env:
        - name: PORT
          value: "{{tag ' .Values.service.servicePort '}}"
        - name: APPLICATION_NAME
          value: "{{tag ' .Release.Name '}}"
        image: "{{tag ' .Values.image.repository '}}:{{tag ' .Values.image.tag '}}"
        imagePullPolicy: {{tag ' .Values.image.pullPolicy '}}
        name: "{{tag '  .Chart.Name  '}}"
{{tag ' if .Values.istio.enabled '}}
{{tag ' else '}}
        readinessProbe:
          httpGet:
          {{#has application.language 'JAVA'}}
            path: /{{#if healthEndpoint}}{{healthEndpoint}}{{else}}health{{/if}}
            port: 9080
            scheme: HTTP
          {{/has}}
          {{#has application.language 'SPRING'}}
            path: /{{#if healthEndpoint}}{{healthEndpoint}}{{else}}health{{/if}}
            port: 8080
            scheme: HTTP
          {{/has}}
          initialDelaySeconds: 20
{{tag ' end '}}
        resources:
          requests:
            cpu: "{{tag ' .Values.image.resources.requests.cpu '}}"
            memory: "{{tag ' .Values.image.resources.requests.memory '}}"
