version: '2'
template:
  name: "Functions {{deployment.name}}"
  description: "Deploy your Cloud Functions for {{deployment.name}} app."
  required:
    - repo
    - build

toolchain:
  name: {{deployment.name}}

services:

  # Github repos
  repo:
    service_id: hostedgit
    parameters:
      repo_url: "{{tag '#zip_url'}}{{tag 'zip_url'}}{{tag '/zip_url'}}{{tag '^zip_url'}}{{tag 'repository'}}{{tag '/zip_url'}}"
      repo_name: "{{tag 'toolchain.name'}}"
      type: {{repoType}}
      has_issues: true
      enable_traceability: true

  # Pipelines
  build:
    service_id: pipeline
    parameters:
      services: 
        - repo
      name: "{{tag 'toolchain.name'}}"
      ui-pipeline: true
      configuration:
        content: 
          $text: pipeline.yml
        env:
          REPO: repo
          CF_APP: "{{tag 'form.pipeline.parameters.app-name'}}"
          CF_SPACE: "{{tag 'form.pipeline.parameters.dev-space'}}"
          CF_ORGANIZATION: "{{tag 'form.pipeline.parameters.dev-organization'}}"
          API_KEY: "{{tag 'form.pipeline.parameters.api-key'}}"
          REGION_ID: "{{tag 'form.pipeline.parameters.dev-region'}}"
        execute: true

  #Web IDE
  webide:
    service_id: orion

#Deployment
form:
  pipeline:
    schema:
      $ref: deploy.json
    parameters:
      app-name: {{name}}
      dev-space: "{{space}}"
      dev-organization: "{{org}}"
      dev-region: "{{region}}"
      api-key: "{{tag 'api-key'}}"
